version: "3.9"

services:
  postgres:
    image: postgres:16-alpine
    container_name: postgres-comissao
    environment:
      POSTGRES_DB: comissaodb
      POSTGRES_USER: comissao
      POSTGRES_PASSWORD: comissao
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
